### ISSUE TITLE
Protect main branch against the ability to push directly to it

### ISSUE THREAD

**Issue by alxedelweiss** [gingkolane/Flatiron-Hackonomics-2024#6]
I believe we need an admin access to that so Chloe @gingkolane

**Comment by isaacsong1** [comment]
Agreed

**Comment by gingkolane** [comment]
Thanks. On it.

**Comment by gingkolane** [comment]
<img width="772" alt="Screenshot 2024-03-13 at 5 08 34 PM" src="https://github.com/gingkolane/Flatiron-Hackonomics-2024/assets/48110809/bf66a6d7-3964-41c5-b504-a3172aceaf5f">
<img width="772" alt="Screenshot 2024-03-13 at 5 08 50 PM" src="https://github.com/gingkolane/Flatiron-Hackonomics-2024/assets/48110809/db218870-30d8-4718-8a2a-4b1a14bfcb65">
require one approval OK?
